# -*- coding: utf-8 -*-
"""normalize_log.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CHUNzFOV_0fXcAlf2relShiQiqfCReY8
"""

### Pre-processing pipeline 2
def normalize_log(image):
     MIN_BOUND = -250
     MAX_BOUND = 1500
     image = (image - MIN_BOUND) / (MAX_BOUND - MIN_BOUND)
     image[image>1] = 1.
     image[image<0] = 0.
     image = (image*255).astype('uint8')
     return image
def log_transform(image):
     c = 255 / log(1 + 255)
     log_image = c * (np.log(image + 1))
     log_image = np.array(log_image, dtype = np.uint8)
     return log_image
#### Pipeline 2 extract images (normalize_log)
#Extract, pre-process and save 2D slice with nodule

# Read nodules csv
csvlines = readCsv('/content/gdrive/MyDrive/training_data_lung_nodule/trainNodules.csv')
header = csvlines[0]
nodules = csvlines[1:]

for n in nodules:
     lnd = int(n[header.index('LNDbID')])
     rad = int(n[header.index('RadID')])
     finding = int(n[header.index('FindingID')])

     if int(n[header.index('LNDbID')])==lnd and int(n[header.index('RadID')])==rad and int(n[header.index('FindingID')])==finding:
         ctr = np.array([float(n[header.index('x')]), float(n[header.index('y')]), float(n[header.index('z')])])
         class_label = np.array([int(n[header.index('Nodule')])])

         name = lnd
     if name in confirmed.index:

         [scan,spacing,origin,transfmat] = readMhd(f'/content/gdrive/MyDrive/training_data_lung_nodule/train/LNDb-{lnd:04}.mhd'.format(lnd=lnd))
         transfmat_toimg,transfmat_toworld = getImgWorldTransfMats(spacing,transfmat)
         ctr = convertToImgCoord(ctr,origin,transfmat_toimg)

         # 2D slice with nodule center
         scan_slice = scan[int(ctr[2])]
         scan_norm = normalize_log(scan_slice)
         scan_norm_log = log_transform(scan_norm)

         # Previous slice
         scan_slice_previous = scan[int(ctr[2])-1]
         scan_norm_pre = normalize_log(scan_slice_previous)
         scan_norm_log_pre = log_transform(scan_norm_pre)

         # Next slice
         scan_slice_next = scan[int(ctr[2])+1]
         scan_norm_next = normalize_log(scan_slice_next)
         scan_norm_log_next = log_transform(scan_norm_next)

         # Resize the image
         width = 512
         height = 512
         dim = (height, width)
         resized = cv2.resize(scan_norm_log, dim, interpolation = cv2.INTER_AREA)
         resized_previous = cv2.resize(scan_norm_log_pre, dim, interpolation = cv2.INTER_AREA)
         resized_next = cv2.resize(scan_norm_log_next, dim, interpolation = cv2.INTER_AREA)

         # Create a 3 channel RBG image
         R = np.stack((resized_previous, resized, resized_next), axis=2)

         # Save the 3 channel images as jpg
         cv2.imwrite(f'/content/train_jpg/normalize_log/LNDb-{lnd:04d}_finding{finding}_rad{rad}.jpg'.format(lnd=lnd,finding=finding,rad=rad), R)